tests/shellcheck_shell_files: warn about 'echo "$variable"' usage
This usage is dangerous, as it can lead to unexpected behavior when
$variable starts with -e or -n.

diff --git a/bin/asciitable b/bin/asciitable
--- a/bin/asciitable
+++ b/bin/asciitable
@@ -93,7 +93,7 @@ do
             USE_LATIN1=true
             ;;
         \?)
-            echo >&2 "$0: invalid option '$OPTARG'"
+            printf >&2 "%s: invalid option '%s'"\\n "$0" "$OPTARG"
             echo >&2 "Try '$0 -h' for more information."
             exit 1
             ;;
diff --git a/bin/denastify-ssh b/bin/denastify-ssh
--- a/bin/denastify-ssh
+++ b/bin/denastify-ssh
@@ -68,7 +68,7 @@ do
             SSH_PORT="$OPTARG"
             ;;
         \?)
-            echo >&2 "$0: invalid option '$OPTARG'"
+            printf >&2 "%s: invalid option '%s'"\\n "$0" "$OPTARG"
             echo >&2 "Try '$0 -h' for more information."
             exit 1
             ;;
@@ -91,16 +91,16 @@ SSH_HOST="$1"
 OUTPUT="$(LANG=C ssh -p "$SSH_PORT" "$SSH_HOST" exit < /dev/null 2>&1)"
 SSH_EXITCODE=$?
 
-if echo "$OUTPUT" | grep -q 'IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!'
+if printf %s\\n "$OUTPUT" | grep -q 'IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!'
 then
     # Retrieve the information which is needed to denastify the host
-    KNOWN_HOST_INFO="$(echo "$OUTPUT" | sed -n 's/^Offending .* key in //p')"
+    KNOWN_HOST_INFO="$(printf %s\\n "$OUTPUT" | sed -n 's/^Offending .* key in //p')"
     KH_PATH="${KNOWN_HOST_INFO%:*}"
-    KH_LINE="$(echo "${KNOWN_HOST_INFO##*:}" | tr -c -d 0-9)"
+    KH_LINE="$(printf %s\\n "${KNOWN_HOST_INFO##*:}" | tr -c -d 0-9)"
     if [ -z "$KH_PATH" ] || [ -z "$KH_LINE" ] || ! [ "$KH_LINE" -ge 0 ]
     then
         echo >&2 "Error: unable to retrieve known_hosts information from message:"
-        echo >&2 "$OUTPUT"
+        printf %s\\n >&2 "$OUTPUT"
         exit 1
     elif [ "$KH_PATH" != "$HOME/.ssh/known_hosts" ]
     then
diff --git a/bin/iommu-show b/bin/iommu-show
--- a/bin/iommu-show
+++ b/bin/iommu-show
@@ -200,7 +200,7 @@ do
             SHOW_DEVICES=true
             ;;
         \?)
-            echo >&2 "$0: invalid option '$OPTARG'"
+            printf >&2 "%s: invalid option '%s'"\\n "$0" "$OPTARG"
             echo >&2 "Try '$0 -h' for more information."
             exit 1
             ;;
@@ -224,7 +224,7 @@ then
     do
         if ! [ -e "$IOMMUDIR" ]
         then
-            echo >&2 "$IOMMUDIR does not exist"
+            printf %s\\n >&2 "$IOMMUDIR does not exist"
             continue
         fi
         IOMMUDEVNAME="${IOMMUDIR##*/}"
@@ -235,7 +235,7 @@ then
             DOMSUPP="$(cat "$IOMMUDIR/intel-iommu/domains_supported")"
             DESC="$DESC: Intel IOMMU, domains $DOMUSED/$DOMSUPP"
         fi
-        echo "$DESC"
+        printf %s\\n "$DESC"
         IS_FIRST_LINE=false
     done
 fi
@@ -244,7 +244,7 @@ for GROUPDIR in /sys/kernel/iommu_groups/*
 do
     if ! [ -e "$GROUPDIR" ]
     then
-        echo >&2 "$GROUPDIR does not exist"
+        printf %s\\n >&2 "$GROUPDIR does not exist"
         continue
     fi
     # Put a blank like between groups
diff --git a/bin/iptables-stats b/bin/iptables-stats
--- a/bin/iptables-stats
+++ b/bin/iptables-stats
@@ -49,15 +49,15 @@ ipt_stats() {
     # Get active chains, which contains at least one active rule
     for LINE in $(run_ipt_nomatch "$IPT --numeric" | tr ' ' '_')
     do
-        if echo "$LINE" | grep -qE '^Chain_'
+        if printf %s\\n "$LINE" | grep -qE '^Chain_'
         then
-            CURRENT_CHAIN=$(echo "$LINE" | sed -n 's/^Chain_\(.*\)_(.*/\1/p')
+            CURRENT_CHAIN=$(printf %s\\n "$LINE" | sed -n 's/^Chain_\(.*\)_(.*/\1/p')
             if [ -z "$CURRENT_CHAIN" ]
             then
                 echo >&2 "Unable to parse chain header line: $LINE"
                 return 1
             fi
-        elif [ -n "$CURRENT_CHAIN" ] && echo "$LINE" | grep -qE '^_*[0-9]'
+        elif [ -n "$CURRENT_CHAIN" ] && printf %s\\n "$LINE" | grep -qE '^_*[0-9]'
         then
             # We have a line which is not empty, show current chain
             # Replace "Chain ..." header line with "IPv4/6 Chain"
@@ -108,7 +108,7 @@ do
             RUN_IP4='false'
             ;;
         \?)
-            echo >&2 "$0: invalid option -- '$OPTARG'"
+            printf >&2 "%s: invalid option '%s'"\\n "$0" "$OPTARG"
             echo >&2 "Try '$0 -h' for more information."
             exit 1
             ;;
diff --git a/bin/luksfile b/bin/luksfile
--- a/bin/luksfile
+++ b/bin/luksfile
@@ -70,7 +70,7 @@ do
             DO_XDGOPEN=false
             ;;
         \?)
-            echo >&2 "$0: invalid option '$OPTARG'"
+            printf >&2 "%s: invalid option '%s'"\\n "$0" "$OPTARG"
             echo >&2 "Try '$0 -h' for more information."
             exit 1
             ;;
@@ -79,12 +79,12 @@ done
 shift $((OPTIND-1))
 if "$DO_MOUNT" && "$DO_UMOUNT"
 then
-    echo >&2 "$0: conflicting options -m and -u"
+    printf %s\\n >&2 "$0: conflicting options -m and -u"
     exit 1
 fi
 if "$DO_KEEPASS" && "$DO_UMOUNT"
 then
-    echo >&2 "$0: conflicting options -k and -u"
+    printf %s\\n >&2 "$0: conflicting options -k and -u"
     exit 1
 fi
 
@@ -144,7 +144,7 @@ luksfile_file() {
         # The file was already mounted, ask to umount it
         if "$DO_MOUNT"
         then
-            echo "$LUKS_FILE is already decrypted."
+            printf %s\\n "$LUKS_FILE is already decrypted."
         elif "$DO_UMOUNT" || ask_umount "$LUKS_FILE"
         then
             if grep -q "$DEVMAP_PATH" /proc/self/mountinfo
@@ -169,7 +169,7 @@ luksfile_file() {
     elif "$DO_UMOUNT"
     then
         # The device mapper does not exist, nothing to do.
-        echo "$LUKS_FILE is not mounted, doing nothing."
+        printf %s\\n "$LUKS_FILE is not mounted, doing nothing."
         return
     else
         # Mount the encrypted file, via a loop device
@@ -203,7 +203,7 @@ luksfile_file() {
             echo "You may now mount the volume with:"
             echo "sudo mount '$DEVMAP_PATH' '$MOUNTPOINT' -o nodev,noexec,nosuid"
             echo "or add such a line to your /etc/fstab:"
-            echo "$DEVMAP_PATH $MOUNTPOINT auto defaults,user,nodev,noexec,nosuid,noauto 0 0"
+            echo " $DEVMAP_PATH $MOUNTPOINT auto defaults,user,nodev,noexec,nosuid,noauto 0 0"
             return
         fi
     fi
diff --git a/bin/vagrant-wireshark b/bin/vagrant-wireshark
--- a/bin/vagrant-wireshark
+++ b/bin/vagrant-wireshark
@@ -53,7 +53,7 @@ do
             MACHINE="$OPTARG"
             ;;
         \?)
-            echo >&2 "$0: invalid option '$OPTARG'"
+            printf >&2 "%s: invalid option '%s'"\\n "$0" "$OPTARG"
             echo >&2 "Try '$0 -h' for more information."
             exit 1
             ;;
diff --git a/dotfiles/shell/functions b/dotfiles/shell/functions
--- a/dotfiles/shell/functions
+++ b/dotfiles/shell/functions
@@ -166,17 +166,17 @@ get_https_cert() {
 get_https_cert_proxy() {
     local S_CLIENT_PROXY
     S_CLIENT_PROXY="$(
-        (
-            echo "${https_proxy-}" ;
-            echo "${HTTPS_PROXY-}" ;
-            echo "${all_proxy-}" ;
-            echo "${ALL_PROXY-}"
-        ) | \
+        printf %s\\n%s\\n%s\\n%s\\n \
+            "${https_proxy-}" \
+            "${HTTPS_PROXY-}" \
+            "${all_proxy-}" \
+            "${ALL_PROXY-}" \
+            | \
         sed -n 's,^\(http://\)\?\([0-9a-zA-Z._-]\+:[0-9]\+\)\(/\)\?$,\2,p' | \
         sed -n 1p)"
     if [ -z "$S_CLIENT_PROXY" ] ; then
-        echo >&2 "Unable to find the proxy settings"
-        exit 1
+        echo >&2 "Unable to parse HTTPS proxy settings"
+        return 1
     fi
     openssl s_client -servername "$1" -connect "$1:443" < /dev/null \
          -proxy "$S_CLIENT_PROXY" \
@@ -209,9 +209,9 @@ postless() {
     STATUS=$?
     # Use less only if postcat succeeded
     if [ "$STATUS" -eq 0 ] ; then
-        echo "$OUTPUT" |less
+        printf %s\\n "$OUTPUT" |less
     else
-        echo "$OUTPUT"
+        printf %s\\n "$OUTPUT"
         return $STATUS
     fi
 }
@@ -230,13 +230,13 @@ case $(grep --help 2> /dev/null) in
                 local FILE
                 FILE="$(mktemp)"
                 # shellcheck disable=SC2064
-                trap "/bin/rm -f \"$FILE\"" EXIT HUP INT QUIT TERM
+                trap "/bin/rm -f -- \"$FILE\"" EXIT HUP INT QUIT TERM
                 while [ $# -ge 1 ] ; do
-                    echo "$1" >> "$FILE"
+                    printf %s\\n "$1" >> "$FILE"
                     shift
                 done
                 \grep -E --color=always -e '' -f "$FILE"
-                /bin/rm "$FILE"
+                /bin/rm -- "$FILE"
             }
         fi
         ;;
@@ -299,7 +299,7 @@ print_args_or_stdin() {
         cat
     else
         while [ $# -ge 1 ] ; do
-            echo "$1"
+            printf %s\\n "$1"
             shift
         done
     fi
