bin/compile-netbpf: suppress tcpdump's annoying first line

diff --git a/bin/compile-netbpf b/bin/compile-netbpf
--- a/bin/compile-netbpf
+++ b/bin/compile-netbpf
@@ -37,5 +37,11 @@
 #   0c: 00000000  timestamp accuracy
 #   10: ffff0000  maximum length of captured packets (65536)
 #   14: 01000000  link-layer header type (ethernet)
-echo '1MOyoQIABAAAAAAAAAAAAP//AAABAAAA' |base64 -d | \
-tcpdump -r /proc/self/fd/0 -d "$@"
+echo '1MOyoQIABAAAAAAAAAAAAP//AAABAAAA' | base64 -d | \
+(
+    # Suppress the annoying first line tcpdump sends to stderr, but keep the
+    # exit code while using a pipe
+    set -o pipefail
+    tcpdump -r /proc/self/fd/0 -d "$@" 2>&1 >&3 | \
+    sed '1{/^reading from file [^ ]*, link-type EN10MB (Ethernet)$/d}' >&2
+) 3>&1
