bin/ping6-local: fix MAC address computations and always print the built IPv6 LL-addr
Signed-off-by: Nicolas Iooss <nicolas.iooss_git@polytechnique.org>

diff --git a/bin/ping6-local b/bin/ping6-local
--- a/bin/ping6-local
+++ b/bin/ping6-local
@@ -141,7 +141,7 @@ ip6_to_ip6ll() {
         echo "$1%$IFACE"
         return
     fi
-    echo $1
+    echo "$1"
 }
 
 # Extract options as $OPTIONS $TARGET "$@"
@@ -172,17 +172,22 @@ if [ -z "$DEST" ]
 then
     echo >&2 "Invalid destination: $1"
     exit 1
-fi
-shift
-
-# Let's try ndisc6 before ping6
-if which ndisc6 > /dev/null 2>&1
+elif echo "$DEST" |grep -q '%'
 then
-    echo -n 'NDISC6 '
-    if ! ndisc6 $(echo $DEST | tr '%' ' ')
+    # Check interface with ndisc6 before ping6
+    if which ndisc6 > /dev/null 2>&1
     then
-        echo >&2 "ndisc6 failed!"
-        exit 1
+        echo -n 'NDISC6 '
+        if ! ndisc6 $(echo $DEST | tr '%' ' ')
+        then
+            echo >&2 "ndisc6 failed!"
+            exit 1
+        fi
     fi
+else
+    echo "Unable to find interface for address $DEST"
+    echo "Try pinging anyway..."
 fi
+
+shift
 exec ping6 $OPTIONS $DEST "$@"
