bin/ping6-local: try ndisc6 before ping6 to avoid non-allocated link-local addresses
Signed-off-by: Nicolas Iooss <nicolas.iooss_git@polytechnique.org>

diff --git a/bin/ping6-local b/bin/ping6-local
--- a/bin/ping6-local
+++ b/bin/ping6-local
@@ -165,4 +165,15 @@ then
     exit 1
 fi
 shift
+
+# Let's try ndisc6 before ping6
+if which ndisc6 2> /dev/null > /dev/null
+then
+    echo -n 'NDISC6 '
+    if ! ndisc6 $(echo $DEST | tr '%' ' ')
+    then
+        echo >&2 "ndisc6 failed!"
+        exit 1
+    fi
+fi
 exec ping6 $OPTIONS $DEST $*
